language: node_js

notifications:
  email:
    - eward.song@gmail.com

node_js:
  - 0.10
  - 0.11

before_install:
  - sudo add-apt-repository ppa:danmbox/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install php5 pngquant php5-gd default-jre

install:
  - npm install

script:
  - make test
